// Package fsxtest holds the one helper every backend test needs: gunzip a
// committed fixture image (fsx/testdata/*.img.gz, generated by gen.sh with
// the real formatting tools) into a temp file and hand back a ReaderAt.
package fsxtest

import (
	"compress/gzip"
	"io"
	"os"
	"path/filepath"
	"testing"
)

// Open gunzips testdata/<name>.img.gz (relative to the calling package's
// directory via rel, e.g. "../testdata") into t.TempDir and opens it.
func Open(t *testing.T, rel, name string) (*os.File, int64) {
	t.Helper()
	src, err := os.Open(filepath.Join(rel, name+".img.gz"))
	if err != nil {
		t.Fatalf("fixture %s: %v (run fsx/testdata/gen.sh)", name, err)
	}
	defer src.Close()
	zr, err := gzip.NewReader(src)
	if err != nil {
		t.Fatal(err)
	}
	dst := filepath.Join(t.TempDir(), name+".img")
	out, err := os.Create(dst)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := io.Copy(out, zr); err != nil {
		t.Fatal(err)
	}
	if err := out.Close(); err != nil {
		t.Fatal(err)
	}
	f, err := os.Open(dst)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { f.Close() })
	st, err := f.Stat()
	if err != nil {
		t.Fatal(err)
	}
	return f, st.Size()
}
